**Task 1 :- Generating random numbers using Numpy**

In [1]:
import numpy as np
ran_no = np.random.rand()
print(ran_no)
ran_arr = np.random.rand(5)
print(ran_arr)
ran_2D_arr = np.random.rand(3,2)
print(ran_2D_arr)
ran_int = np.random.randint(1,10)
print(ran_int)
ran_int_arr = np.random.randint(1, 10, size=5)
print(ran_int_arr)

0.8125371553230609
[0.11999142 0.40782836 0.27435363 0.38806786 0.08980811]
[[0.07799726 0.80570382]
 [0.7394506  0.78105803]
 [0.93897033 0.52987933]]
5
[9 6 9 5 5]


**Task 2 :- Generate array and slicing a Numpy array**

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11])
print(arr)

slice_arr = arr[2:6]
print(slice_arr)

slice_arr2 = arr[:5]
print(slice_arr2)

slice_arr3 = arr[4:]
print(slice_arr3)

slice_arr4 = arr[2:9:2]
print(slice_arr4)

[ 1  2  3  4  5  6  7  8  9 10 11]
[3 4 5 6]
[1 2 3 4 5]
[ 5  6  7  8  9 10 11]
[3 5 7 9]


**Task 3 :- Concatenating two Numpy arrays**

In [3]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([7, 8, 9])

concatinate_arr = np.concatenate((arr1 , arr2))
print(concatinate_arr)

[1 2 3 7 8 9]


**Task 4 :- Sorting a Numpy array**

In [8]:
import numpy as np 
arr = np.array([3, 1, 5, 2, 4])

sorted_arr = np.sort(arr)
print(sorted_arr)

sorted_arr_desc = np.sort(arr)[::-1]
print(sorted_arr_desc)

[1 2 3 4 5]
[5 4 3 2 1]
